### ISSUE TITLE
npm3 support for parent property

### ISSUE THREAD

**Issue by davej** [npm/read-package-tree#9] opened 2016-01-16 12:27 UTC
In `npm3` the parent property is always set to the top-level ancestor rather than the immediate parent. This may be a wontfix since this module just reads the directory structure but I wanted to document this anyway.

**Comment by iarna** [comment] 2016-06-23 23:56
You may be interested to know that read-package-tree is only used in npm@3.

Relatedly, the trees read-package-tree produces are the physical filesystem trees, so parent always refers to where the module is on disk, regardless of relationships they have.

npm@3 does build a relationship tree internally but currently that's buried in its source. We do intend to extract that out at some point however.

As this isn't a bug (but rather, its intended behavior), I'm going to close the issue.

**Closed as completed by iarna** 2016-06-23 23:56 UTC
